name: tea4chat-external-fullstack
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tea4chat
    volumes:
      - ./services/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # CAVEAT: This container rely on the server folder being in the same directory
  # as the docker-compose file. You should bun install under the server folder
  # before running this container. You should also have a .env file in the
  # server folder with the correct environment variables.
  migration:
    image: oven/bun:latest
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tea4chat
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../server:/app
      - ../server/node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        apt-get update -y && apt-get install -y openssl &&
        echo 'Installing dependencies...' &&
        echo 'Generating Prisma Client...' &&
        bun prisma generate &&
        echo 'Running database migrations...' &&
        bun prisma migrate deploy &&
        echo 'Running database seeding...' &&
        bun prisma db seed &&
        echo 'Migration and seeding completed successfully!'
      "
    restart: "no"

volumes:
  postgres_data:
  redis_data:
